export const cities = [
  "Copenhagen",
  "Frederiksberg",
  "Albertslund",
  "Karlshus",
  "Moss",
  "Oslo",
  "Frogner",
  "Drammen",
  "Vestby",
  "Aursmoen",
  "Tranby",
  "Bergen",
  "Sarpsborg",
  "Kongsvinger",
  "Asgardstrand",
  "Kolbotn",
  "Horten",
  "Lysaker",
  "Nesbru",
  "Skarnes",
  "Aseral",
  "Stokke",
  "Hammerfest",
  "Askim",
  "Sortland",
  "Leknes",
  "Rygge",
  "Leirsund",
  "Dal",
  "Raholt",
  "Dilling",
  "Elverum",
  "Trondheim",
  "Kolsas",
  "Fornebu",
  "Skien",
  "Finnsnes",
  "Tomasjorda",
  "Tromsdalen",
  "Hovik verk",
  "Stabekk",
  "Oppegard",
  "Arendal",
  "Salhus",
  "Hol",
  "Gjerdrum",
  "Fetsund",
  "Molde",
  "Skodje",
  "Fosnavag",
  "Brattvag",
  "Langevag",
  "Syvik",
  "Vestnes",
  "Volda",
  "Ulsteinvik",
  "Eide",
  "Hareid",
  "Stranda",
  "Stordal",
  "Hjelset",
  "Tennfjord",
  "Lyngstad",
  "Kristiansund",
  "Rovde",
  "Aukra",
  "Skotterud",
  "Moelv",
  "Magnor",
  "Brumunddal",
  "Harstad",
  "Larvik",
  "Andalsnes",
  "Ski",
  "Halden",
  "Sandefjord",
  "Fredrikstad",
  "Porsgrunn",
  "Baerums verk",
  "Tertnes",
  "Rjukan",
  "Holmestrand",
  "Lillehammer",
  "Krakeroy",
  "Rolvsoy",
  "Saltnes",
  "Haukeland",
  "Ranheim",
  "Jessheim",
  "Sandvika",
  "Haslum",
  "Asker",
  "Langhus",
  "Stavern",
  "Gressvik",
  "Kragero",
  "Nevlunghamn",
  "Hamar",
  "Ottestad",
  "Arnes",
  "Gran",
  "Mo i Rana",
  "Frekhaug",
  "Eidsvoll verk",
  "Kristiansand",
  "Narvik",
  "Tokyo",
  "Hiroshima",
  "Saitama",
  "Nihon'odori",
  "Ibaraki",
  "Urayasu",
  "Suita",
  "Funabashi",
  "Nagareyama",
  "Ichikawa",
  "Isesaki",
  "Koga",
  "Ichihara",
  "Koshigaya",
  "Shibukawa",
  "Aoicho",
  "Yamakita",
  "Gotemba",
  "Nisshin",
  "Nishinomiya",
  "Den'en-chofu",
  "Kawasaki",
  "Toyama-shi",
  "Moriguchi",
  "Chita",
  "Sano",
  "Shizuoka",
  "Kawanishi",
  "Itami",
  "Kobe",
  "Tokai",
  "Guangzhou",
  "Fuzhou",
  "Beijing",
  "Baotou",
  "Hohhot",
  "Guiyang",
  "Yinchuan",
  "Nanjing",
  "Changzhou",
  "Chuzhou",
  "Bangkok",
  "Chumphon",
  "Kathu",
  "Phang Khon",
  "Sakon Nakhon",
  "Mueang Nonthaburi",
  "Kalasin",
  "Chon Buri",
  "Loei",
  "Khon Kaen",
  "Nong Bua Lamphu",
  "Roi Et",
  "Udon Thani",
  "Kumphawapi",
  "Kanchanaburi",
  "Nong Khai",
  "Ayutthaya",
  "Chiang Mai",
  "Fairfield",
  "Chicago",
  "Hernando",
  "Irving",
  "Baltimore",
  "Kingston",
  "Burlington",
  "Harrison",
  "Newton Center",
  "Littleton",
  "Bloomington",
  "San Ramon",
  "Downers Grove",
  "Circleville",
  "Oxnard",
  "Gulfport",
  "Portland",
  "Houston",
  "Greenbank",
  "Somerset",
  "Sidman",
  "Minneapolis",
  "Manchester",
  "Canton",
  "The Bronx",
  "San Francisco",
  "Saluda",
  "San Jose",
  "Santa Clara",
  "Sunnyvale",
  "Washington",
  "Harrisburg",
  "Stafford",
  "Newington",
  "Vienna",
  "Cambridge",
  "Boston",
  "South Harwich",
  "Worcester",
  "Tampa",
  "Lake Wales",
  "Saint Petersburg",
  "Kyle",
  "Pomona",
  "Covina",
  "Edmonds",
  "Kirkland",
  "White Plains",
  "Waynesboro",
  "Buffalo",
  "New York",
  "Ridgewood",
  "Utica",
  "Port Washington",
  "Brecksville",
  "Streetsboro",
  "Hartford",
  "Nashville",
  "Chester",
  "Richmond",
  "Jacksonville",
  "Kissimmee",
  "Clinton",
  "Denver",
  "Fort Worth",
  "Brandon",
  "Dover",
  "Union Township",
  "Nazareth",
  "Pine Brook",
  "Edison",
  "Redwood City",
  "Arvada",
  "Pineville",
  "Ponte Vedra Beach",
  "Sarasota",
  "Jackson",
  "Nacogdoches",
  "Tomball",
  "McKinney",
  "Little Rock",
  "Dallas",
  "Halethorpe",
  "Crofton",
  "Northbrook",
  "Palatine",
  "New Hyde Park",
  "Phoenix",
  "Northville",
  "St Louis",
  "Lafayette",
  "Castle Rock",
  "Windsor",
  "Laurel",
  "Collegeville",
  "Twinsburg",
  "Getzville",
  "Richfield",
  "Rochester",
  "Lorton",
  "Manassas",
  "Virginia Beach",
  "Waldorf",
  "Ashburn",
  "Seattle",
  "Woodbridge",
  "Verona",
  "Bakersfield",
  "Scranton",
  "Riverside",
  "Gardena",
  "Bakersfield",
  "Fontana",
  "Los Angeles",
  "Sacramento",
  "Bonham",
  "Keller",
  "Orlando",
  "Largo",
  "Austin",
  "Atlanta",
  "Salem",
  "Stockbridge",
  "Monroe Township",
  "Lakewood",
  "San Diego",
  "Spring Valley",
  "Reseda",
  "Oak Brook",
  "Novi",
  "Miami",
  "Fort Lauderdale",
  "Littleton",
  "Southern Pines",
  "Grantville",
  "Honesdale",
  "Philadelphia",
  "Coatesville",
  "Kennesaw",
  "Irvine",
  "Newbury Park",
  "Ontario",
  "Manhattan Beach",
  "San Mateo",
  "Westlake Village",
  "Covington",
  "Wichita",
  "Canton",
  "Euless",
  "New Orleans",
  "Garland",
  "Poughkeepsie",
  "Mechanicsville",
  "Sterling",
  "Temple Hills",
  "Glen Allen",
  "Hopkins",
  "Jersey City",
  "Parsippany",
  "Wanaque",
  "Whippany",
  "Bothell",
  "Mill Valley",
  "Oakland",
  "Canonsburg",
  "Naperville",
  "Columbus",
  "Monmouth Junction",
  "King of Prussia",
  "Tipton",
  "Trenton",
  "Upland",
  "Santa Monica",
  "Hacienda Heights",
  "Lewis Center",
  "Alexandria",
  "Fairfax",
  "Frederick",
  "Dumfries",
  "Charlotte",
  "Bradenton",
  "Winchester",
  "Anniston",
  "Round Rock",
  "Humble",
  "Katy",
  "Golden",
  "Colorado Springs",
  "Merrick",
  "Northfield",
  "Ridgefield Park",
  "North Palm Beach",
  "Boca Raton",
  "High Bridge",
  "Piscataway",
  "Hillsborough",
  "Huntington Beach",
  "Tempe",
  "Yorba Linda",
  "Duarte",
  "Oceanside",
  "Redding",
  "Fountain Valley",
  "Clinton",
  "Durham",
  "Marysville",
  "Long Island City",
  "Haverford",
  "League City",
  "Jackson",
  "Berkley",
  "Plano",
  "Lexington",
  "Atlanta",
  "Brighton",
  "Wakefield",
  "East Falmouth",
  "Louisa",
  "Gaithersburg",
  "Ashland",
  "Columbia",
  "Upper Marlboro",
  "Oviedo",
  "Birmingham",
  "Tallahassee",
  "Tustin",
  "Suwanee",
  "Pompano Beach",
  "Grapevine",
  "Pittsburgh",
  "Butler",
  "South Jordan",
  "Elk Grove Village",
  "Milwaukee",
  "Bradford",
  "Villa Park",
  "Springfield Township",
  "South Amboy",
  "Signal Hill",
  "Wilmington",
  "Newport Beach",
  "Las Vegas",
  "Portsmouth",
  "Midlothian",
  "Rockville",
  "Newport News",
  "Edison",
  "Paul Smiths",
  "Copenhagen",
  "North Richland Hills",
  "Cedar Hill",
  "Moorestown Township",
  "Huntsville",
  "Silver Spring",
  "Fayetteville",
  "Raleigh",
  "Chesapeake",
  "Arlington",
  "Rougemont",
  "Annandale",
  "Norcross",
  "Hendersonville",
  "Dalton",
  "Brooklyn",
  "Elmhurst",
  "Terre Haute",
  "Ingleside",
  "Detroit",
  "Baton Rouge",
  "West Hollywood",
  "New Albany",
  "Louisville",
  "Destrehan",
  "Normal",
  "Ludington",
  "Zolfo Springs",
  "Zephyrhills",
  "Bowling Green",
  "Coppell",
  "Chestnut Hill",
  "Dedham",
  "Westborough",
  "Andover",
  "Jasper",
  "Allentown",
  "Greensburg",
  "South Burlington",
  "Warrendale",
  "Reston",
  "New Kensington",
  "Pitcairn",
  "Hanover",
  "Duncansville",
  "Englewood",
  "Boulder",
  "Seoul",
  "Incheon",
  "Manila",
  "Moscow",
  "Omsk",
  "Peschanka",
  "Novovarshavka",
  "Luzino",
  "Vienenburg",
  "Rosdorf",
  "Einbeck",
  "Markersbach",
  "Westensee",
  "Lauterbach",
  "Marburg",
  "Dornburg",
  "Mainz",
  "Weinbach",
  "Cologne",
  "Stockholm",
  "Uppsala",
  "Malmo",
  "Handen",
  "Skaerholmen",
  "Gothenburg",
  "Lidingoe",
  "Rome",
  "Amsterdam",
  "The Hague",
  "Zoetermeer",
  "Helmond",
  "Beek",
  "Breukelen",
  "Almere",
  "Valencia",
  "Riola",
  "Barcelona",
  "Athens",
  "Pershore",
  "Rowley Regis",
  "Stroud",
  "Birmingham",
  "Worcester",
  "Smethwick",
  "Alcester",
  "Dudley",
  "Gloucester",
  "Solihull",
  "Tamworth",
  "Abu Dhabi",
  "Riyadh"
];
